import { v4 as uuidv4 } from "uuid";

function chillHop() {
  return [
    {
      name: "01 Al-Fatiha",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/SlMv8z3.png",
      id: uuidv4(),
      active: true,
      color: ["#696464", "#395944"],
      audio: "https://freequranmp3.com/alafasy/001-al-fatihah.mp3",
    },
    {
      name: "02 Al-Baqarah",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/7Trxhuv.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#01253D"],
      audio: "https://freequranmp3.com/alafasy/002-al-baqarah.mp3",
    },
    {
      name: "03 Al-'Imran",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/EuQZd6O.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#3A1914"],
      audio: "https://freequranmp3.com/alafasy/003-al-imran.mp3",
    },
    {
      name: "04 An-Nisa'",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/duaJ3pL.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#3F0A3E"],
      audio: "https://freequranmp3.com/alafasy/004-an-nisa.mp3",
    },
    {
      name: "05 Al-Ma'idah",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/vcjCz7e.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#0E2E17"],
      audio: "https://freequranmp3.com/alafasy/005-al-maidah.mp3",
    },
    {
      name: "06 Al-An'am",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/rk94K4k.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#504613"],
      audio: "https://freequranmp3.com/alafasy/006-al-anam.mp3",
    },
    {
      name: "07 Al-A'raf",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/CIO6PVM.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#A0450E"],
      audio: "https://freequranmp3.com/alafasy/007-al-araf.mp3",
    },
    {
      name: "08 Al-Anfal",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/Ki3OqLS.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#B21212"],
      audio: "https://freequranmp3.com/alafasy/008-al-anfal.mp3",
    },
    {
      name: "09 At-Taubah",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/eJ4Ebus.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#82F5A8"],
      audio: "https://freequranmp3.com/alafasy/009-at-taubah.mp3",
    },
    {
      name: "10 Yunus",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/TG8FVec.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#BC77BC"],
      audio: "https://freequranmp3.com/alafasy/010-yunus.mp3",
    },
    {
      name: "11 Hud",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/crCOawB.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#D7F8A1"],
      audio: "https://freequranmp3.com/alafasy/011-hud.mp3",
    },
    {
      name: "12 Yusuf",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/mcR39nZ.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#FEA500"],
      audio: "https://freequranmp3.com/alafasy/012-yusuf.mp3",
    },
    {
      name: "13 Ar-Rad",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/P5LmKG9.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#B6C2F6"],
      audio: "https://freequranmp3.com/alafasy/013-ar-rad.mp3",
    },
    {
      name: "14 Ibrahim",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/YJy4GWH.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#152EA2"],
      audio: "https://freequranmp3.com/alafasy/014-ibrahim.mp3",
    },
    {
      name: "15 Al-Hijr",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/iAzB2kA.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#610536"],
      audio: "https://freequranmp3.com/alafasy/015-al-hijr.mp3",
    },
    {
      name: "16 An-Nahl",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/wsXvQtw.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#F6D530"],
      audio: "https://freequranmp3.com/alafasy/016-an-nahl.mp3",
    },
    {
      name: "17 An-Isra",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/UHq6OXf.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#000000"],
      audio: "https://freequranmp3.com/alafasy/017-al-isra.mp3",
    },
    {
      name: "18 Al-Kahf",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/LfRkB2L.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#410F58"],
      audio: "https://freequranmp3.com/alafasy/018-al-kahf.mp3",
    },
    {
      name: "19 Maryam",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/j4k6Diw.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#FF8371"],
      audio: "https://freequranmp3.com/alafasy/019-maryam.mp3",
    },
    {
      name: "20 Ta-Ha",
      artist: "Sheikh Mishary Rashid Al-Afasy",
      cover: "https://i.imgur.com/0FRhezo.png",
      id: uuidv4(),
      active: false,
      color: ["#696464", "#404040"],
      audio: "https://freequranmp3.com/alafasy/020-ta-ha.mp3",
    },
  ];
}

export default chillHop;